--
-- V4 — Multitenancy por organização (grupos).
--
-- Novas tabelas: organizacoes, membros_organizacao, convites_organizacao.
-- Todas as tabelas de negócio ganham organizacao_id (nullable aqui; o
-- DataInitializer faz o backfill dos dados existentes e o transforma em
-- NOT NULL em runtime).
-- As uniques globais de codigo/numero/cnpj/edital viram uniques POR
-- organização, e usuarios.perfil passa a aceitar SUPER_ADMIN | USUARIO.
--

-- Organizações (grupos)
CREATE TABLE public.organizacoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome character varying(120) NOT NULL,
    criado_por bigint NOT NULL REFERENCES public.usuarios(id),
    criado_em timestamp(6) without time zone NOT NULL DEFAULT now()
);

-- Papel do usuário DENTRO da organização
CREATE TABLE public.membros_organizacao (
    organizacao_id bigint NOT NULL REFERENCES public.organizacoes(id),
    usuario_id bigint NOT NULL REFERENCES public.usuarios(id),
    papel character varying(20) NOT NULL,
    desde timestamp(6) without time zone NOT NULL DEFAULT now(),
    CONSTRAINT membros_organizacao_pkey PRIMARY KEY (organizacao_id, usuario_id),
    CONSTRAINT membros_organizacao_papel_check
        CHECK (papel IN ('ADMIN', 'OPERADOR', 'VISITANTE'))
);

-- Convites: por e-mail (convite pendente) ou por código
CREATE TABLE public.convites_organizacao (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacao_id bigint NOT NULL REFERENCES public.organizacoes(id),
    email character varying(150),
    codigo character varying(24),
    papel character varying(20) NOT NULL,
    criado_por bigint NOT NULL REFERENCES public.usuarios(id),
    criado_em timestamp(6) without time zone NOT NULL DEFAULT now(),
    usado_em timestamp(6) without time zone,
    CONSTRAINT convites_organizacao_papel_check
        CHECK (papel IN ('ADMIN', 'OPERADOR', 'VISITANTE'))
);

CREATE UNIQUE INDEX uk_convites_organizacao_codigo
    ON public.convites_organizacao(codigo) WHERE codigo IS NOT NULL;
CREATE INDEX ix_convites_organizacao_email ON public.convites_organizacao(email);

-- Perfil global: SUPER_ADMIN | USUARIO (papel de negócio vive na organizacao)
ALTER TABLE public.usuarios DROP CONSTRAINT IF EXISTS usuarios_perfil_check;
UPDATE public.usuarios SET perfil = 'SUPER_ADMIN' WHERE perfil = 'ADMIN';
ALTER TABLE public.usuarios ADD CONSTRAINT usuarios_perfil_check
    CHECK (perfil IN ('SUPER_ADMIN', 'USUARIO'));

-- Coluna organizacao_id nas tabelas de negócio (nullable até o backfill)
ALTER TABLE public.dotacoes_orcamentarias
    ADD COLUMN organizacao_id bigint REFERENCES public.organizacoes(id);
ALTER TABLE public.fornecedores
    ADD COLUMN organizacao_id bigint REFERENCES public.organizacoes(id);
ALTER TABLE public.licitacoes
    ADD COLUMN organizacao_id bigint REFERENCES public.organizacoes(id);
ALTER TABLE public.contratos
    ADD COLUMN organizacao_id bigint REFERENCES public.organizacoes(id);
ALTER TABLE public.empenhos
    ADD COLUMN organizacao_id bigint REFERENCES public.organizacoes(id);
ALTER TABLE public.creditos_suplementares
    ADD COLUMN organizacao_id bigint REFERENCES public.organizacoes(id);

-- Uniques global → única por organização
-- (IF EXISTS: em bancos baselined as uniques antigas podem não existir por nome)
ALTER TABLE public.dotacoes_orcamentarias DROP CONSTRAINT IF EXISTS uk_dotacoes_codigo;
ALTER TABLE public.dotacoes_orcamentarias
    ADD CONSTRAINT uk_dotacoes_org_codigo UNIQUE (organizacao_id, codigo);

ALTER TABLE public.fornecedores DROP CONSTRAINT IF EXISTS uk_fornecedores_cnpj;
ALTER TABLE public.fornecedores
    ADD CONSTRAINT uk_fornecedores_org_cnpj UNIQUE (organizacao_id, cnpj);

ALTER TABLE public.licitacoes DROP CONSTRAINT IF EXISTS uk_licitacoes_edital;
ALTER TABLE public.licitacoes
    ADD CONSTRAINT uk_licitacoes_org_edital UNIQUE (organizacao_id, numero_edital);

ALTER TABLE public.contratos DROP CONSTRAINT IF EXISTS uk_contratos_numero;
ALTER TABLE public.contratos
    ADD CONSTRAINT uk_contratos_org_numero UNIQUE (organizacao_id, numero);

-- Índices para as buscas por organização
CREATE INDEX idx_dotacoes_organizacao ON public.dotacoes_orcamentarias(organizacao_id);
CREATE INDEX idx_fornecedores_organizacao ON public.fornecedores(organizacao_id);
CREATE INDEX idx_licitacoes_organizacao ON public.licitacoes(organizacao_id);
CREATE INDEX idx_contratos_organizacao ON public.contratos(organizacao_id);
CREATE INDEX idx_empenhos_organizacao ON public.empenhos(organizacao_id);
CREATE INDEX idx_creditos_organizacao ON public.creditos_suplementares(organizacao_id);