--
-- V7 — Melhorias de conta e convites.
--
-- usuarios.genero: saudação "Bem-vindo(a)" (M/F/não informado).
-- convites_organizacao.expira_em: convite por código expira (default 7 dias);
-- convite por e-mail (expira_em nulo) continua sem expirar.
-- recuperacao_senha: código de recuperação guardado apenas como SHA-256 (hex),
-- com expiração, contador de tentativas e uso único. Novo pedido descarta o anterior.
--

-- Gênero para saudação (opcional, default "não informado")
ALTER TABLE public.usuarios
    ADD COLUMN genero character varying(20) NOT NULL DEFAULT 'NAO_INFORMADO';
ALTER TABLE public.usuarios
    ADD CONSTRAINT usuarios_genero_check
        CHECK (genero IN ('MASCULINO', 'FEMININO', 'NAO_INFORMADO'));

-- Expiração de convite por código (nulo = e-mail, sem expiração)
ALTER TABLE public.convites_organizacao
    ADD COLUMN expira_em timestamp(6) without time zone;

-- Tokens de recuperação de senha
CREATE TABLE public.recuperacao_senha (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id bigint NOT NULL REFERENCES public.usuarios(id),
    token_hash character varying(64) NOT NULL,
    expira_em timestamp(6) without time zone NOT NULL,
    tentativas integer NOT NULL DEFAULT 0,
    usado_em timestamp(6) without time zone,
    criado_em timestamp(6) without time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uk_recuperacao_senha_usuario_pendente
    ON public.recuperacao_senha(usuario_id) WHERE usado_em IS NULL;